### PR TITLE
Feat UI & i18n

### PR DESCRIPTION
**Pull request by Gloridust**
这个 PR 主要做出了以下更改：
- 更好地设计了 UI，进行了自适应适配；
- 进行了 i18n 多语言支持，在 nav 栏增加了语言选择，并获取用户系统语言作为默认语言，目前适配了中文/ENG 双语
这是一个很好的项目，相信它能获得更多人的喜欢。

This PR mainly makes the following changes:
- The UI is better designed and adaptive adaptation is carried out.
- I18n multilingual support is implemented. Language selection is added to the nav bar, and the user's system language is obtained as the default language. Currently, bilingual support for Chinese/ENG is adapted.
This is a very good project. I believe it can be liked by more people.

Screenshot 2024-10-05 at 00 10 57
Screenshot 2024-10-05 at 00 11 46

### CODE REVIEW

**Comment by Gloridust** [comment]
Sooo sorry that there were some layout problems of nav on small screen devices. I'll fix it tonight.

**Comment by nekomeowww** [comment]
Thanks for contributing.

Please address your PR into seperated "i18n support" and "UI/UX improve" into two for us to review and merge.

Several suggestions:

- Blue scheme is not harmonic to the icon and the current grayish-color scheme, I would suggest not to change the background to blue.
- While your design takes account for different sections of `<nav>`, `<main>` and use of `<select>` which meets the ideal accessibility requirements, I personally would suggest not to divide the **camera option**, **camera** and **ideal scans** sections into different island-looking sections which apparently breaks the semantic of these options and sections for user to understand, and feels like they are not bounded together.
- (I personally think) We were improve our UI/UX progressively and do our best to maintain the theme and design language when we developing during these days. We maintain the themes not just for this project, but also keeping it aligned with other projects we made (such as [talks.antfu.me](https://talks.antfu.me), [qrcode.antfu.me](https://qrcode.antfu.me) and [Nolebase Integrations](https://nolebase-integrations.ayaka.io). I highly recommend you to check out these projects and get the sense of choosing colors, color theme, UI feeling of these projects, then tweak your PR based on the existing references. (It's up to you eventually to decide which is the best option).
- As for i18n switch, ideally, it's not limited to use `<select>` and `<option>` (they are known to be one of the toughest ones to customize on, especially crucial if you are willing to improve the options later. ([vitepress.dev](https://vitepress.dev) or [vitesse](https://vitesse.netlify.app/) might be a better candidate to be referenced with)

And always, thanks for the contribution, if you think the UI/UX suggestion I wrote is a time-consuming step to go for now, you can split your PR into two with i18n support comes first, then focusing on UI/UX improvements later on.

**Comment by Gloridust** [comment]
Ok, thx for your advice. I'll improve these opinions as fast as I can.

**Comment by LittleSound** [comment]
In summary, Please split the PR into multiple independent submissions to reduce our review difficulty. I will close this PR for now. Thank you for your contribution. We look forward to you submitting a more suitable PR.

**Pull request closed without merging**
